<?xml version="1.0" encoding="UTF-8"?><testrun name="M3PublicTests" project="harrypotter" tests="83" started="83" failures="3" errors="0" ignored="0">
  <testsuite name="harrypotter.tests.M3PublicTests" time="0.246">
    <testcase name="testSlytherinMovesToWallCellOnTraitActivated" classname="harrypotter.tests.M3PublicTests" time="0.005"/>
    <testcase name="testRelocatingObstacleToCupThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.024"/>
    <testcase name="testUseOnSlytherinWhileInCoolDownThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testRelocatingPotionSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.011"/>
    <testcase name="testInCooldownExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testRelocatingChampionToWallThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.01"/>
    <testcase name="testNotEnoughIPExceptionReqIPGetter" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testCastingDamagingSpellWithNotEnoughIPInFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testMoveOutOfBordersFromCornerSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.004"/>
    <testcase name="testRelocatingObstacleOutOfRangeSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.012"/>
    <testcase name="testSlytherinMovesToTreasureCellOnTraitActivated" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testInCooldownExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testInvalidActionExceptionAbstract" classname="harrypotter.tests.M3PublicTests" time="0.003"/>
    <testcase name="testDamagingCupCellThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.011"/>
    <testcase name="testNotEnoughIPExceptionReqIPSetter" classname="harrypotter.tests.M3PublicTests" time="0.002"/>
    <testcase name="testOutOfBordersExceptionConstructorExists2" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testRelocatingChampionToCollectibleSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.007"/>
    <testcase name="testSlytherinMovesToCellOutOfBordersOnTraitActivatedSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.003">
      <failure>java.lang.AssertionError: In the class harrypotter.model.tournament.SecondTask, when slytherin trait is activated in the Left direction, and the target cell is out of the borders, OutOfBordersException should be thrown
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M3PublicTests.SlytherinMovesToCellOutOfBordersOnTraitActivatedHelper(M3PublicTests.java:859)
	at harrypotter.tests.M3PublicTests.testSlytherinMovesToCellOutOfBordersOnTraitActivatedSecondTask(M3PublicTests.java:5098)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testRelocatingObstacleToChampionSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.006"/>
    <testcase name="testRelocatingChampionToObstacleFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.007"/>
    <testcase name="testConstructorInitializationInCooldownException" classname="harrypotter.tests.M3PublicTests" time="0.002"/>
    <testcase name="testUseOnHufflepuffWhileInCoolDownThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <failure>java.lang.AssertionError: In ThirdTask, The Hufflepuff trait should be always activated and should never throw an InCooldownException. harrypotter.exceptions.InCooldownException: Cannot make a move Yet. remaining Turns: -1
	at org.junit.Assert.fail(Assert.java:88)
	at harrypotter.tests.M3PublicTests.testUseOnHufflepuffWhileInCoolDownThirdTask(M3PublicTests.java:5447)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testRelocatingObstacleToObstacleFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.008"/>
    <testcase name="testInvalidActionExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testCastingRelocatingSpellWithNotEnoughIPInFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testOutOfRangeExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testMoveRightToObstacleCell" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testMoveLeftToObstacleCell" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testRelocatingTreasureCellSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.008"/>
    <testcase name="testCastDamagingSpellWhileCoolingDownThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.023"/>
    <testcase name="testConstructorInitializationInvalidTargetCellException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testInvalidTargetCellExceptionConstructorExists2" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testOutOfBordersExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testUseOnHufflepuffWhileInCoolDownFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testOutOfBordersExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testMoveBackwardToIncorrectTreasureCell" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testMoveLeftToWallCell" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testNotEnoughIPExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testConstructorInitializationNotEnoughIPException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testNotEnoughResourcesExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testInvalidActionExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testRelocatingEmptyCellThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.008"/>
    <testcase name="testNotEnoughIPExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testOutOfRangeExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testUseOnGryffindorTraitWhileInCoolDownSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="tesInvalidTargetCellExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testRelocatingChampionOutOfRangeFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.007"/>
    <testcase name="testCastRelocationSpellWhileCoolingDownFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.012"/>
    <testcase name="testCastRelocatingSpellOnTargetOutOfBordersThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.003"/>
    <testcase name="testCastingHealingSpellWithEnoughIP" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testInvalidTargetCellExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testNotEnoughResourcesExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testNotEnoughIPExceptionInstanceVariables1" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testNotEnoughIPExceptionInstanceVariables2" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testRelocatingObstacleToCollectibleThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.005"/>
    <testcase name="testInvalidActionExceptionConstructorExists2" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testDamagingPotionFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.004"/>
    <testcase name="testCastHealingSpellWhileCoolingDownSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.008"/>
    <testcase name="testMoveBackwardToWallCell" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testMoveBackwardToChampionCell" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testNotEnoughResourcesExceptionConstructorExists2" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testMoveForwardToChampionCell" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testUseOnRavenclawWhileInCoolDownThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testNotEnoughIPExceptionRemIPGetter" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testInCooldownExceptionRemTurnsGetter" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testInCooldownExceptionInstanceVariables1" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testOutOfRangeExceptionAllowedRangeGetter" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testNotEnoughIPExceptionRemIPSetter" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testConstructorInitializationOutOfRangeException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testRelocatingChampionOutOfBordersThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.008"/>
    <testcase name="testCastingHealingSpellWithNotEnoughIPInThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testInCooldownExceptionRemTurnsSetter" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testOutOfRangeExceptionAllowedRangeSetter" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testDamagingWallThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.004"/>
    <testcase name="testNotEnoughResourcesExceptionAbstract" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testOutOfRangeExceptionInstanceVariables1" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testMoveOutOfBordersFromEdgeFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testConstructorInitializationOutOfBordersException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testRelocatingObstacleOutOfBordersThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.006"/>
    <testcase name="testMoveForwardToIncorrectTreasureCell" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testCastDamagingSpellOutOfBordersFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.003"/>
    <testcase name="testCastingDamagingSpellWithEnoughIP" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testSlytherinMovesToCupCellOnTraitActivated" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <failure>java.lang.AssertionError: In the ThirdTask, when slytherin trait is activated in the FORWARD direction, and the target cell is CupCell, InvalidTargetCell Exception should be thrown
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M3PublicTests.onSlythMovesToInvalidCellsHelper(M3PublicTests.java:530)
	at harrypotter.tests.M3PublicTests.testSlytherinMovesToCupCellOnTraitActivated(M3PublicTests.java:5127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
  </testsuite>
</testrun>
